from __future__ import annotations

# ACC-REL-001 / ACC-REL-003: presentation-only, snapshot-backed sector drill-down.


def fixed_sector_assets() -> str:
    return r'''<script>
const fixedSectorDefinitions=[
  {id:'ip',label:'同 IP',color:'#60a5fa'}, {id:'cid',label:'CID',color:'#a78bfa'},
  {id:'ea',label:'EA',color:'#22d3ee'}, {id:'copy',label:'跟单',color:'#f472b6'},
  {id:'rebate',label:'返佣',color:'#fbbf24'}, {id:'ib',label:'IB / CRM 归属',color:'#818cf8'},
  {id:'sync',label:'开平仓同步',color:'#fb7185'}, {id:'hedge',label:'反向对锁',color:'#f43f5e'},
];
const fixedSectorTypes={same_crm_user:'center',same_name:'center',login_ip:'ip',client_id:'cid',ea_feature:'ea',copy_order:'copy',copy_group:'copy',rebate:'rebate',crm_owner:'ib',direct_ib:'ib',ib_owned_account:'ib',ib_direct_account:'ib',ib_identity:'ib',ib_direct_rebate:'ib',top_ib_group:'ib',toxic_sync_same:'sync',toxic_sync_opposite:'hedge'};
let fixedSectorActive=false,fixedSectorHit={nodes:[],edges:[],sectors:[]},fixedSectorLocatorHits=[],fixedSectorViewFitted=false,fixedSectorFocusId='',fixedSectorExpandedId='',fixedSectorHistory=[];
function fixedSectorNodes(){return(data?.entities||[]).filter(node=>node.type==='account'||node.type==='ib_user')}
function fixedSectorFocus(){if(!data)return null;const nodes=fixedSectorNodes(),subject=nodes.find(node=>node.isSubject);let focus=byId().get(fixedSectorFocusId);if(!focus||!nodes.some(node=>node.id===focus.id)){focus=subject||nodes[0]||null;fixedSectorFocusId=focus?.id||''}return focus}
function fixedSectorCenterIds(focus){const entities=byId(),ids=new Set(focus?[focus.id]:[]),queue=focus?[focus.id]:[];while(queue.length){const id=queue.shift();for(const edge of data?.relationships||[]){const key=relationKey(edge.type);if(key!=='same_crm_user'&&key!=='same_name')continue;const other=edge.source===id?edge.target:edge.target===id?edge.source:'';const node=entities.get(other);if(node?.type==='account'&&!ids.has(other)){ids.add(other);queue.push(other)}}}return ids}
function fixedSectorProjection(w,h){
  const entities=byId(),focus=fixedSectorFocus(),center=fixedSectorCenterIds(focus),cx=w/2,cy=h/2,outer=Math.min(w,h)*.42,inner=outer*.31;
  const sectors=fixedSectorDefinitions.map((item,index)=>({...item,start:-Math.PI/2+index*Math.PI/4+.025,end:-Math.PI/2+(index+1)*Math.PI/4-.025,items:new Map(),accounts:new Set(),evidence:0})),sectorById=new Map(sectors.map(item=>[item.id,item]));
  for(const raw of data?.relationships||[]){const sectorId=fixedSectorTypes[relationKey(raw.type)],sector=sectorById.get(sectorId);if(!sector||sectorId==='center')continue;const left=entities.get(raw.source),right=entities.get(raw.target);if(!left||!right)continue;let from=null,to=null;if(center.has(left.id)&&!center.has(right.id)){from=left;to=right}else if(center.has(right.id)&&!center.has(left.id)){from=right;to=left}if(!from||!to||!['account','ib_user'].includes(to.type))continue;const item=sector.items.get(to.id)||{node:to,edges:[]};if(!item.edges.some(edge=>String(edge.id)===String(raw.id)))item.edges.push({raw,from});sector.items.set(to.id,item);sector.accounts.add(to.id);sector.evidence++}
  const centerMembers=fixedSectorNodes().filter(node=>center.has(node.id)&&node.id!==focus?.id),centerPoints=new Map();if(focus)centerPoints.set(focus.id,{x:cx,y:cy});centerMembers.forEach((node,index)=>{const angle=-Math.PI/2+index*Math.PI*2/Math.max(1,centerMembers.length);centerPoints.set(node.id,{x:cx+Math.cos(angle)*inner*.66,y:cy+Math.sin(angle)*inner*.66})});
  const occurrences=[],edges=[];for(const sector of sectors){const expanded=fixedSectorExpandedId===sector.id,items=[...sector.items.values()],span=sector.end-sector.start,columns=Math.max(1,Math.min(4,Math.ceil(Math.sqrt(items.length))));items.forEach((item,index)=>{const column=index%columns,row=Math.floor(index/columns),rows=Math.ceil(items.length/columns),angle=sector.start+span*(column+.5)/columns,progress=rows<=1?.5:row/(rows-1),radius=inner+(outer-inner)*(expanded?.42+.46*progress:.50+.24*progress),point={id:'fixed-sector-instance|'+fixedSectorFocusId+'|'+sector.id+'|'+item.node.id,node:item.node,x:cx+Math.cos(angle)*radius,y:cy+Math.sin(angle)*radius,sector:sector.id,detail:expanded};occurrences.push(point);if(expanded)item.edges.forEach(({raw,from})=>edges.push({id:String(raw.id),raw,from:{node:from,...(centerPoints.get(from.id)||{x:cx,y:cy})},to:point,sector:sector.id,directed:isDirectedRelation(raw.type)}))})}
  return{cx,cy,inner,outer,focus,center,centerMembers,centerPoints,sectors,occurrences,edges};
}
function fixedSectorRenderLocator(){const locator=document.getElementById('galaxyLocator'),context=locator?.getContext('2d');if(!locator||!context)return;const rect=locator.getBoundingClientRect(),w=Math.max(1,rect.width),h=Math.max(1,rect.height),d=devicePixelRatio||1,nodeMap=new Map(fixedSectorNodes().filter(node=>node.type==='account').map(node=>[node.id,node])),nodes=[...nodeMap.values()].sort((a,b)=>Number(a.hops||0)-Number(b.hops||0)||String(a.label).localeCompare(String(b.label),undefined,{numeric:true})),cx=w/2,cy=h/2,radius=Math.min(w,h)*.31;locator.width=Math.round(w*d);locator.height=Math.round(h*d);context.setTransform(d,0,0,d,0,0);context.fillStyle='#071426';context.fillRect(0,0,w,h);fixedSectorLocatorHits=[];nodes.forEach((node,index)=>{const point=node.isSubject?{x:cx,y:cy}:{x:cx+Math.cos(index*2.4)*radius,y:cy+Math.sin(index*2.4)*radius};context.beginPath();context.arc(point.x,point.y,node.isSubject?7:4.5,0,Math.PI*2);context.fillStyle=galaxyLocatorStatusColor(node);context.fill();if(node.id===selectedId||node.isSubject){context.strokeStyle='#fff';context.lineWidth=2;context.stroke()}fixedSectorLocatorHits.push({node,x:point.x,y:point.y,radius:12})});const count=document.getElementById('galaxyLocatorCount');if(count)count.textContent=nodes.length+'个账户 · 全部显示'}
function fixedSectorScreenPoint(point){return{x:view.x+point.x*view.scale,y:view.y+point.y*view.scale}}
function fixedSectorRenderControls(focus){const note=document.getElementById('overviewNote');if(note){note.replaceChildren();const text=document.createElement('span');text.textContent='当前中心：'+(focus?.label||'-')+'。首屏显示各扇区的直接第 1 层账户；点击扇区展开该扇区的关系线和证据，点击账户进入其下一层扇区。左侧全局定位图始终显示全部已查询账户。';note.append(text);if(fixedSectorHistory.length){const back=document.createElement('button');back.type='button';back.textContent='返回上一层';back.style.cssText='margin-left:10px;padding:3px 8px;border:1px solid #4da3ff;border-radius:4px;background:#102b48;color:#cfe9ff;cursor:pointer';back.addEventListener('click',()=>{const previous=fixedSectorHistory.pop();if(!previous)return;fixedSectorFocusId=previous;fixedSectorExpandedId='';selectedId=previous;activeType='';selectedEdgeKey='';renderOverview();renderDetail()});note.append(back)}}const head=document.querySelector('.galaxy-center .galaxy-panel-head');if(head?.firstChild)head.firstChild.textContent='固定区域关系网 ';const meta=document.getElementById('galaxyGalaxyMeta');if(meta)meta.textContent='中心：'+(focus?.label||'-')+' · 第 1 层'}
function fixedSectorRenderOverview(){if(!data)return;const rect=canvas.getBoundingClientRect(),p=fixedSectorProjection(Math.max(1,rect.width),Math.max(1,rect.height));fixedSectorActive=true;ctx.fillStyle='#101826';ctx.fillRect(0,0,rect.width,rect.height);ctx.save();ctx.translate(view.x,view.y);ctx.scale(view.scale,view.scale);fixedSectorHit={nodes:[],edges:[],sectors:[]};for(const sector of p.sectors){ctx.beginPath();ctx.arc(p.cx,p.cy,p.outer,sector.start,sector.end);ctx.arc(p.cx,p.cy,p.inner,sector.end,sector.start,true);ctx.closePath();const expanded=fixedSectorExpandedId===sector.id;ctx.fillStyle=sector.evidence?(expanded?'rgba(40,94,190,.34)':'rgba(30,58,138,.16)'):'rgba(51,65,85,.08)';ctx.fill();ctx.strokeStyle=sector.color;ctx.lineWidth=expanded?2.5:1.2;ctx.stroke();const angle=(sector.start+sector.end)/2,labelPoint={x:p.cx+Math.cos(angle)*(p.outer+20),y:p.cy+Math.sin(angle)*(p.outer+20)};ctx.fillStyle=sector.evidence?sector.color:'#64748b';ctx.font='700 11px Microsoft YaHei';ctx.textAlign='center';ctx.fillText(sector.label+' · '+sector.accounts.size+'账户 / '+sector.evidence+'关系'+(expanded?' · 已展开':''),labelPoint.x,labelPoint.y);ctx.textAlign='start';const hitPoint=fixedSectorScreenPoint({x:p.cx+Math.cos(angle)*(p.inner+p.outer)*.5,y:p.cy+Math.sin(angle)*(p.inner+p.outer)*.5});fixedSectorHit.sectors.push({id:sector.id,accounts:sector.accounts.size,evidence:sector.evidence,x:hitPoint.x,y:hitPoint.y,expanded,start:sector.start,end:sector.end,inner:p.inner,outer:p.outer,cx:p.cx,cy:p.cy})}for(const edge of p.edges){ctx.beginPath();ctx.moveTo(edge.from.x,edge.from.y);ctx.lineTo(edge.to.x,edge.to.y);ctx.strokeStyle=p.sectors.find(item=>item.id===edge.sector)?.color||'#93c5fd';ctx.lineWidth=2;ctx.stroke();fixedSectorHit.edges.push({edge,points:[fixedSectorScreenPoint(edge.from),fixedSectorScreenPoint(edge.to)],tolerance:12})}const paint=(node,point,radius,sector)=>{if(!node)return;drawNode(node,point.x,point.y,radius);ctx.fillStyle=color(node);ctx.fill();ctx.strokeStyle=node.id===selectedId?'#fff':'#bde7ff';ctx.stroke();drawActionBadge(node,point.x,point.y,radius);const screen=fixedSectorScreenPoint(point);fixedSectorHit.nodes.push({node,x:screen.x,y:screen.y,radius:(radius+9)*view.scale,sector})};paint(p.focus,{x:p.cx,y:p.cy},19,'center');p.centerMembers.forEach(node=>paint(node,p.centerPoints.get(node.id),11,'center'));p.occurrences.forEach(item=>paint(item.node,item,item.detail?10:7,item.sector));ctx.restore();fixedSectorRenderControls(p.focus);fixedSectorRenderLocator()}
function fixedSectorPointInSector(point,sector){const x=(point.x-view.x)/view.scale-sector.cx,y=(point.y-view.y)/view.scale-sector.cy,radius=Math.hypot(x,y);let angle=Math.atan2(y,x);if(angle<sector.start)angle+=Math.PI*2;return radius>=sector.inner&&radius<=sector.outer&&angle>=sector.start&&angle<=sector.end}
function fixedSectorDrillInto(node){const focus=fixedSectorFocus();if(node.id!==focus?.id){fixedSectorHistory.push(focus.id);fixedSectorFocusId=node.id}fixedSectorExpandedId='';selectedId=node.id;activeType='';selectedEdgeKey='';renderOverview();renderDetail()}
function galaxyFixedSectorDispatch(event){if(!fixedSectorActive)return false;const rect=galaxyCanvas.getBoundingClientRect(),point={x:event.clientX-rect.left,y:event.clientY-rect.top};for(const hit of fixedSectorHit.nodes)if(Math.hypot(point.x-hit.x,point.y-hit.y)<=hit.radius){fixedSectorDrillInto(hit.node);return true}for(const hit of fixedSectorHit.edges)if(galaxyScreenDistanceToSegment(point,hit.points[0],hit.points[1])<=hit.tolerance){selectedEdgeKey=hit.edge.id;activeType='';inspectionSkipNextRefresh=true;renderOverview();renderDetail();inspectionLoadRelation(hit.edge.raw);return true}for(const sector of fixedSectorHit.sectors)if(fixedSectorPointInSector(point,sector)){fixedSectorExpandedId=fixedSectorExpandedId===sector.id?'':sector.id;renderOverview();renderDetail();return true}return true}
const fixedSectorLocator=document.getElementById('galaxyLocator');fixedSectorLocator?.addEventListener('click',event=>{if(!fixedSectorActive)return;const rect=fixedSectorLocator.getBoundingClientRect(),point={x:event.clientX-rect.left,y:event.clientY-rect.top},hit=fixedSectorLocatorHits.find(item=>Math.hypot(point.x-item.x,point.y-item.y)<=item.radius);if(!hit)return;event.preventDefault();event.stopImmediatePropagation();fixedSectorDrillInto(hit.node)},true);
window.__kdeskFixedSectorTestFrame=()=>({revision:Number(data?.revision||0),inProgress:Boolean(data?.inProgress),focusAccountId:String(fixedSectorFocus()?.id||''),expandedSector:fixedSectorExpandedId,nodes:fixedSectorHit.nodes.map(item=>({accountId:String(item.node.id),nodeType:String(item.node.type),sector:item.sector,x:item.x,y:item.y,radius:item.radius})),edges:fixedSectorHit.edges.map(item=>({id:item.edge.id,type:String(item.edge.raw.type),sector:item.sector,from:item.points[0],to:item.points[1]})),sectors:fixedSectorHit.sectors.map(item=>({id:item.id,accounts:item.accounts,evidence:item.evidence,accountIds:(fixedSectorProjection(canvas.getBoundingClientRect().width,canvas.getBoundingClientRect().height).sectors.find(sector=>sector.id===item.id)?.accounts? [...fixedSectorProjection(canvas.getBoundingClientRect().width,canvas.getBoundingClientRect().height).sectors.find(sector=>sector.id===item.id).accounts]:[]).map(String),x:item.x,y:item.y,expanded:item.expanded})),locatorAccountIds:fixedSectorLocatorHits.map(item=>String(item.node.id))});
if(params.get('graph_type')==='fixed-sector'){fitMapToBoard=function(){if(!fixedSectorViewFitted){view={scale:1,x:0,y:0};fixedSectorViewFitted=true}};renderOverview=fixedSectorRenderOverview;const fixedDetailBase=renderDetail;renderDetail=function(){fixedDetailBase();groups?.querySelectorAll('.group-toggle').forEach(item=>item.remove())};}
</script>'''
