from __future__ import annotations

# ACC-REL-001 / ACC-REL-003: presentation-only fixed-area Galaxy projection.


def fixed_sector_assets() -> str:
    return r'''<script>
const fixedSectorDefinitions=[{id:'ip',label:'同 IP',color:'#60a5fa'},{id:'cid',label:'CID',color:'#a78bfa'},{id:'ea',label:'EA',color:'#22d3ee'},{id:'copy',label:'跟单',color:'#f472b6'},{id:'rebate',label:'返佣',color:'#fbbf24'},{id:'ib',label:'IB / CRM 归属',color:'#818cf8'},{id:'sync',label:'开平仓同步',color:'#fb7185'},{id:'hedge',label:'反向对锁',color:'#f43f5e'}];
const fixedSectorTypes={same_crm_user:'center',same_name:'center',login_ip:'ip',client_id:'cid',ea_feature:'ea',copy_order:'copy',copy_group:'copy',rebate:'rebate',crm_owner:'ib',direct_ib:'ib',ib_owned_account:'ib',ib_direct_account:'ib',ib_identity:'ib',ib_direct_rebate:'ib',top_ib_group:'ib',toxic_sync_same:'sync',toxic_sync_opposite:'hedge'};
let fixedSectorActive=false,fixedSectorHit={nodes:[],edges:[]},fixedSectorViewFitted=false;
function fixedSectorNodes(){return(data?.entities||[]).filter(node=>node.type==='account'||node.type==='ib_user')}
function fixedSectorCenter(){const subject=fixedSectorNodes().find(node=>node.isSubject),ids=new Set(subject?[subject.id]:[]),queue=subject?[subject.id]:[],entities=byId();while(queue.length){const id=queue.shift();for(const edge of data?.relationships||[]){if(relationKey(edge.type)!=='same_crm_user')continue;const other=edge.source===id?edge.target:edge.target===id?edge.source:'';if(entities.get(other)?.type==='account'&&!ids.has(other)){ids.add(other);queue.push(other)}}}return ids}
function fixedSectorProjection(w,h){const nodes=fixedSectorNodes(),subject=nodes.find(node=>node.isSubject),center=fixedSectorCenter(),cx=w/2,cy=h/2,outer=Math.min(w,h)*.42,inner=outer*.34,sectors=fixedSectorDefinitions.map((item,index)=>({...item,start:-Math.PI/2+index*Math.PI/4+.025,end:-Math.PI/2+(index+1)*Math.PI/4-.025,branches:new Map(),accounts:new Set(),evidence:0})),sectorById=new Map(sectors.map(item=>[item.id,item])),occurrences=[],edges=[],seen=new Set(),entities=byId();for(const raw of data?.relationships||[]){const id=fixedSectorTypes[relationKey(raw.type)];if(!id||id==='center'||seen.has(String(raw.id)))continue;const a=entities.get(raw.source),b=entities.get(raw.target),sector=sectorById.get(id);if(!a||!b||!sector)continue;seen.add(String(raw.id));sector.evidence++;for(const node of[a,b])if(!center.has(node.id)&&node.type==='account')sector.accounts.add(node.id);let source=a,target=b;if(center.has(b.id)&&!center.has(a.id)){source=b;target=a}const branch=sector.branches.get(source.id)||{source,items:[]};branch.items.push({target,raw});sector.branches.set(source.id,branch)}for(const sector of sectors){const branches=[...sector.branches.values()],span=sector.end-sector.start;branches.forEach((branch,index)=>{const angle=sector.start+span*(index+.5)/Math.max(1,branches.length),entry={id:'fixed-sector-entry|'+sector.id+'|'+branch.source.id,x:cx+Math.cos(angle)*(inner+12),y:cy+Math.sin(angle)*(inner+12),label:'来自中心：'+branch.source.label,sector:sector.id};const source=center.has(branch.source.id)?entry:{id:'fixed-sector-instance|'+sector.id+'|'+branch.source.id,node:branch.source,x:cx+Math.cos(angle)*(inner+(outer-inner)*.34),y:cy+Math.sin(angle)*(inner+(outer-inner)*.34),sector:sector.id};if(source.node)occurrences.push(source);branch.items.forEach((item,itemIndex)=>{if(center.has(item.target.id))return;const offset=(itemIndex%3-1)*.1,target={id:'fixed-sector-instance|'+sector.id+'|'+branch.source.id+'|'+item.target.id+'|'+itemIndex,node:item.target,x:cx+Math.cos(angle+offset)*(outer-12-Math.floor(itemIndex/3)*20),y:cy+Math.sin(angle+offset)*(outer-12-Math.floor(itemIndex/3)*20),sector:sector.id};occurrences.push(target);edges.push({id:String(item.raw.id),raw:item.raw,from:source,to:target,sector:sector.id,directed:isDirectedRelation(item.raw.type)})})})}const centerMembers=nodes.filter(node=>center.has(node.id)&&node.id!==subject?.id);return{cx,cy,inner,outer,subject,center,centerMembers,sectors,occurrences,edges}}
function fixedSectorRenderLocator(){const canvas=document.getElementById('galaxyLocator'),context=canvas?.getContext('2d');if(!canvas||!context)return;const rect=canvas.getBoundingClientRect(),w=Math.max(1,rect.width),h=Math.max(1,rect.height),d=devicePixelRatio||1,nodes=fixedSectorNodes().filter(node=>node.type==='account').sort((a,b)=>Number(a.hops||0)-Number(b.hops||0)||String(a.label).localeCompare(String(b.label),undefined,{numeric:true})),cx=w/2,cy=h/2;canvas.width=Math.round(w*d);canvas.height=Math.round(h*d);context.setTransform(d,0,0,d,0,0);context.fillStyle='#071426';context.fillRect(0,0,w,h);galaxyLocatorHitNodes=[];nodes.forEach((node,index)=>{const point=node.isSubject?{x:cx,y:cy}:{x:cx+Math.cos(index*2.4)*Math.min(w,h)*.3,y:cy+Math.sin(index*2.4)*Math.min(w,h)*.3};context.beginPath();context.arc(point.x,point.y,node.isSubject?7:4.5,0,Math.PI*2);context.fillStyle=galaxyLocatorStatusColor(node);context.fill();galaxyLocatorHitNodes.push({id:node.id,x:point.x,y:point.y,radius:12})});const count=document.getElementById('galaxyLocatorCount');if(count)count.textContent=nodes.length+'个账户 · 去重定位'}
function fixedSectorRenderOverview(){if(!data)return;const rect=canvas.getBoundingClientRect(),p=fixedSectorProjection(Math.max(1,rect.width),Math.max(1,rect.height));fixedSectorActive=true;ctx.fillStyle='#101826';ctx.fillRect(0,0,rect.width,rect.height);ctx.save();ctx.translate(view.x,view.y);ctx.scale(view.scale,view.scale);fixedSectorHit={nodes:[],edges:[]};for(const sector of p.sectors){ctx.beginPath();ctx.arc(p.cx,p.cy,p.outer,sector.start,sector.end);ctx.arc(p.cx,p.cy,p.inner,sector.end,sector.start,true);ctx.closePath();ctx.fillStyle=sector.evidence?'rgba(30,58,138,.18)':'rgba(51,65,85,.11)';ctx.fill();ctx.strokeStyle=sector.color;ctx.lineWidth=1.2;ctx.stroke();const a=(sector.start+sector.end)/2;ctx.fillStyle=sector.evidence?sector.color:'#64748b';ctx.font='700 11px Microsoft YaHei';ctx.textAlign='center';ctx.fillText(sector.label+' · '+sector.accounts.size+'账户 / '+sector.evidence+'关系',p.cx+Math.cos(a)*(p.outer+18),p.cy+Math.sin(a)*(p.outer+18));ctx.textAlign='start'}for(const edge of p.edges){ctx.beginPath();ctx.moveTo(edge.from.x,edge.from.y);ctx.lineTo(edge.to.x,edge.to.y);ctx.strokeStyle=p.sectors.find(item=>item.id===edge.sector)?.color||'#93c5fd';ctx.lineWidth=2;ctx.stroke();fixedSectorHit.edges.push({edge,points:[{x:view.x+edge.from.x*view.scale,y:view.y+edge.from.y*view.scale},{x:view.x+edge.to.x*view.scale,y:view.y+edge.to.y*view.scale}],tolerance:12})}const paint=(node,point,radius,sector)=>{if(!node)return;drawNode(node,point.x,point.y,radius);ctx.fillStyle=color(node);ctx.fill();ctx.strokeStyle=node.id===selectedId?'#fff':'#bde7ff';ctx.stroke();drawActionBadge(node,point.x,point.y,radius);fixedSectorHit.nodes.push({node,x:view.x+point.x*view.scale,y:view.y+point.y*view.scale,radius:(radius+9)*view.scale,sector})};paint(p.subject,{x:p.cx,y:p.cy},19,'center');p.centerMembers.forEach((node,index)=>{const a=-Math.PI/2+index*Math.PI*2/Math.max(1,p.centerMembers.length);paint(node,{x:p.cx+Math.cos(a)*p.inner*.72,y:p.cy+Math.sin(a)*p.inner*.72},11,'center')});p.occurrences.forEach(item=>paint(item.node,item,10,item.sector));ctx.restore();const note=document.getElementById('overviewNote');if(note)note.textContent='固定区域关系网：中心只显示问题账户和同名账户；外部按关系固定分区。点击关系线查看原始证据。';const meta=document.getElementById('galaxyGalaxyMeta');if(meta)meta.textContent='固定区域关系网';fixedSectorRenderLocator()}
function galaxyFixedSectorDispatch(event){if(!fixedSectorActive)return false;const rect=galaxyCanvas.getBoundingClientRect(),point={x:event.clientX-rect.left,y:event.clientY-rect.top};for(const hit of fixedSectorHit.nodes)if(Math.hypot(point.x-hit.x,point.y-hit.y)<=hit.radius){selectedId=hit.node.id;activeType='';selectedEdgeKey='';renderOverview();renderDetail();return true}for(const hit of fixedSectorHit.edges)if(galaxyScreenDistanceToSegment(point,hit.points[0],hit.points[1])<=hit.tolerance){selectedEdgeKey=hit.edge.id;activeType='';renderOverview();renderDetail();inspectionLoadRelation(hit.edge.raw);return true}return true}
window.__kdeskFixedSectorTestFrame=()=>({revision:Number(data?.revision||0),inProgress:Boolean(data?.inProgress),nodes:fixedSectorHit.nodes.map(item=>({accountId:String(item.node.id),sector:item.sector,x:item.x,y:item.y,radius:item.radius})),edges:fixedSectorHit.edges.map(item=>({id:item.edge.id,type:String(item.edge.raw.type),sector:item.edge.sector,from:item.points[0],to:item.points[1]}))});
fitMapToBoard=function(){if(!fixedSectorViewFitted){view={scale:1,x:0,y:0};fixedSectorViewFitted=true}};renderOverview=fixedSectorRenderOverview;const fixedDetailBase=renderDetail;renderDetail=function(){fixedDetailBase();groups?.querySelectorAll('.group-toggle').forEach(item=>item.remove())};
</script>'''
