from __future__ import annotations


def render_kuzu_demo_page() -> str:
    return """<!doctype html>
<html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Kuzu 关系图试用</title><style>
:root{font-family:"Microsoft YaHei",Arial,sans-serif;color:#e6edf3;background:#171a1f}*{box-sizing:border-box}body{margin:0;min-height:100vh}.bar{height:58px;display:flex;align-items:center;gap:16px;padding:0 24px;border-bottom:1px solid #343941;background:#20242a}.brand{font-size:17px;font-weight:700}.tag{font-size:12px;color:#99d8c9;border:1px solid #367b6e;padding:4px 8px}.spacer{flex:1}.muted{font-size:12px;color:#aeb7c2}.layout{display:grid;grid-template-columns:minmax(0,1fr) 310px;min-height:calc(100vh - 58px)}.stage{min-width:0;padding:18px 20px 20px}.controls{display:flex;align-items:center;gap:14px;min-height:40px;margin-bottom:12px}.segment{display:inline-flex;border:1px solid #404750}.segment button{min-width:58px;border:0;border-right:1px solid #404750;background:#252a31;color:#b9c3cf;padding:8px 12px;cursor:pointer}.segment button:last-child{border-right:0}.segment button.active{background:#17695d;color:#fff}.filters{display:flex;align-items:center;gap:8px;flex-wrap:wrap}.filter{display:inline-flex;align-items:center;gap:5px;font-size:12px;color:#c6cfd8}.filter input{accent-color:#3bb79e}.canvas-wrap{height:calc(100vh - 132px);min-height:560px;border:1px solid #383f48;background:#1c2026;overflow:hidden}.canvas-wrap canvas{width:100%;height:100%;display:block;touch-action:none;cursor:grab}.canvas-wrap canvas.drag{cursor:grabbing}.detail{border-left:1px solid #343941;background:#20242a;padding:22px;overflow:auto}.eyebrow{font-size:12px;color:#75cdbb}.detail h1{font-size:19px;margin:8px 0 18px;letter-spacing:0}.metric{display:grid;grid-template-columns:1fr 1fr;border-top:1px solid #343941;border-bottom:1px solid #343941;padding:13px 0;margin-bottom:20px}.metric b{display:block;font-size:19px;margin-top:3px}.selection{font-size:14px;line-height:1.6}.selection h2{font-size:15px;margin:4px 0 8px}.selection p{margin:5px 0;color:#b8c3cf}.selection ul{margin:9px 0;padding-left:18px;color:#cbd5df}.error{color:#ffb4a7}.legend{display:flex;gap:11px;flex-wrap:wrap;font-size:12px;color:#aeb7c2}.dot{width:9px;height:9px;display:inline-block;border-radius:50%;margin-right:4px}@media(max-width:900px){.layout{grid-template-columns:1fr}.detail{border-left:0;border-top:1px solid #343941}.canvas-wrap{height:560px}.bar{padding:0 14px}.stage{padding:14px}.controls{align-items:flex-start;flex-direction:column;gap:8px}}
</style></head><body><header class="bar"><div class="brand">Kuzu 关系图试用</div><span class="tag">本机只读缓存</span><span class="spacer"></span><span class="muted" id="status">读取本地图谱...</span></header><main class="layout"><section class="stage"><div class="controls"><div class="segment" aria-label="展开层级"><button data-depth="1">一层</button><button data-depth="2" class="active">二层</button><button data-depth="3">三层</button></div><div class="filters" id="filters"></div></div><div class="canvas-wrap"><canvas id="graph" aria-label="Kuzu 账户关系图"></canvas></div></section><aside class="detail"><div class="eyebrow">本地 Kuzu 投影</div><h1 id="account">-</h1><div class="metric"><div><span class="muted">实体</span><b id="entities">-</b></div><div><span class="muted">关系</span><b id="relationships">-</b></div></div><div class="selection" id="selection"><h2>选择节点或连线</h2><p>显示该事实的来源与证据。</p></div></aside></main><script>
const canvas=document.getElementById('graph'),ctx=canvas.getContext('2d'),status=document.getElementById('status'),filters=document.getElementById('filters'),selection=document.getElementById('selection');
const colors={account:'#54b2ff',ip:'#e6a84a',ea_feature:'#d77ec8',copy_group:'#9b87e8',rebate:'#f17474',copy_order:'#69c6a6',same_crm_user:'#a6c5ff',login_ip:'#e6a84a'};
const typeLabels={account:'交易账户',ip:'登录 IP',ea_feature:'EA / 路由特征',copy_group:'跟单组',rebate:'返佣',copy_order:'跟单订单',same_crm_user:'同 CRM 客户',login_ip:'登录 IP'};
const state={data:null,depth:2,types:new Set(),positions:new Map(),camera:{x:0,y:0,scale:1},pointer:null,dragNode:null,selected:null,frame:0};
function typeLabel(value){return typeLabels[value]||value}
function resize(){const rect=canvas.getBoundingClientRect(),ratio=devicePixelRatio||1;canvas.width=Math.round(rect.width*ratio);canvas.height=Math.round(rect.height*ratio);ctx.setTransform(ratio,0,0,ratio,0,0);requestPaint()}window.addEventListener('resize',resize);
function escapeText(value){return String(value||'')}
function setSelection(title,lines,evidence=[]){selection.replaceChildren();const h=document.createElement('h2');h.textContent=title;selection.append(h);for(const line of lines){const p=document.createElement('p');p.textContent=line;selection.append(p)}if(evidence.length){const ul=document.createElement('ul');for(const item of evidence){const li=document.createElement('li');li.textContent=item;ul.append(li)}selection.append(ul)}}
function outgoingDepths(){const subject=state.data.entities.find(item=>item.isSubject);const depths=new Map([[subject.id,0]]),queue=[subject.id];while(queue.length){const id=queue.shift(),current=depths.get(id);for(const edge of state.data.relationships.filter(item=>item.source===id)){if(!depths.has(edge.target)){depths.set(edge.target,current+1);queue.push(edge.target)}}}return depths}
function layout(){if(!state.data)return;const rect=canvas.getBoundingClientRect(),depths=outgoingDepths(),subject=state.data.entities.find(item=>item.isSubject),center={x:rect.width/2,y:rect.height/2};state.positions=new Map([[subject.id,center]]);for(let layer=1;layer<=state.depth;layer++){const items=state.data.entities.filter(item=>depths.get(item.id)===layer),radius=Math.min(rect.width,rect.height)*(0.18+layer*0.18);items.forEach((item,index)=>{const angle=-Math.PI/2+(Math.PI*2*index/Math.max(items.length,1));state.positions.set(item.id,{x:center.x+Math.cos(angle)*radius,y:center.y+Math.sin(angle)*radius})})}}
function visible(){if(!state.data)return {edges:[],nodes:[]};const edges=state.data.relationships.filter(edge=>state.types.has(edge.type)),ids=new Set();for(const edge of edges){ids.add(edge.source);ids.add(edge.target)}const subject=state.data.entities.find(item=>item.isSubject);if(subject)ids.add(subject.id);return {edges,nodes:state.data.entities.filter(node=>ids.has(node.id))}}
function world(point){return{x:(point.x-state.camera.x)/state.camera.scale,y:(point.y-state.camera.y)/state.camera.scale}}function screen(point){return{x:point.x*state.camera.scale+state.camera.x,y:point.y*state.camera.scale+state.camera.y}}
function requestPaint(){if(!state.frame)state.frame=requestAnimationFrame(draw)}
function draw(){state.frame=0;const rect=canvas.getBoundingClientRect(),{edges,nodes}=visible();ctx.clearRect(0,0,rect.width,rect.height);ctx.fillStyle='#1c2026';ctx.fillRect(0,0,rect.width,rect.height);for(const edge of edges){const a=state.positions.get(edge.source),b=state.positions.get(edge.target);if(!a||!b)continue;const p=screen(a),q=screen(b),selected=state.selected?.id===edge.id;ctx.strokeStyle=selected?'#fff':(colors[edge.type]||'#9da8b4');ctx.globalAlpha=selected?1:.62;ctx.lineWidth=selected?2.7:1.4;ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(q.x,q.y);ctx.stroke();if(state.camera.scale>.65){ctx.globalAlpha=.95;ctx.fillStyle='#d4dbe4';ctx.font='11px Microsoft YaHei';ctx.textAlign='center';ctx.fillText(edge.label,(p.x+q.x)/2,(p.y+q.y)/2-6)}}ctx.globalAlpha=1;for(const node of nodes){const pos=state.positions.get(node.id);if(!pos)continue;const p=screen(pos),isSubject=node.isSubject,selected=state.selected?.id===node.id;const radius=isSubject?25:19;ctx.fillStyle=colors[node.type]||'#a4b0bd';ctx.beginPath();ctx.arc(p.x,p.y,radius,0,Math.PI*2);ctx.fill();ctx.strokeStyle=selected?'#fff':'#20242a';ctx.lineWidth=selected?3:2;ctx.stroke();ctx.fillStyle='#eff4f7';ctx.font=(isSubject?'700 ':'')+'12px Microsoft YaHei';ctx.textAlign='center';ctx.fillText(node.label,p.x,p.y+4);if(node.platform||node.server){ctx.fillStyle='#aeb7c2';ctx.font='10px Microsoft YaHei';ctx.fillText([node.platform,node.server].filter(Boolean).join(' · '),p.x,p.y+34)}}}
function hit(point){const {nodes}=visible(),p=world(point);for(const node of nodes){const pos=state.positions.get(node.id),radius=node.isSubject?25:19;if(pos&&Math.hypot(pos.x-p.x,pos.y-p.y)<=radius)return {kind:'node',item:node}}for(const edge of visible().edges){const a=state.positions.get(edge.source),b=state.positions.get(edge.target);if(!a||!b)continue;const distance=Math.abs((b.y-a.y)*p.x-(b.x-a.x)*p.y+b.x*a.y-b.y*a.x)/Math.hypot(b.y-a.y,b.x-a.x);if(distance<6/state.camera.scale)return {kind:'edge',item:edge}}return null}
canvas.addEventListener('pointerdown',event=>{const rect=canvas.getBoundingClientRect(),point={x:event.clientX-rect.left,y:event.clientY-rect.top},found=hit(point);state.pointer={point,last:point,moved:false};state.dragNode=found?.kind==='node'?found.item:null;canvas.setPointerCapture(event.pointerId);canvas.classList.add('drag')});canvas.addEventListener('pointermove',event=>{if(!state.pointer)return;const rect=canvas.getBoundingClientRect(),point={x:event.clientX-rect.left,y:event.clientY-rect.top},dx=point.x-state.pointer.last.x,dy=point.y-state.pointer.last.y;state.pointer.moved||=Math.hypot(point.x-state.pointer.point.x,point.y-state.pointer.point.y)>3;if(state.dragNode){const pos=world(point);state.positions.set(state.dragNode.id,pos)}else{state.camera.x+=dx;state.camera.y+=dy}state.pointer.last=point;requestPaint()});canvas.addEventListener('pointerup',event=>{if(!state.pointer)return;const rect=canvas.getBoundingClientRect(),point={x:event.clientX-rect.left,y:event.clientY-rect.top};if(!state.pointer.moved){const found=hit(point);if(found){state.selected={id:found.item.id};if(found.kind==='node'){setSelection(found.item.label,[typeLabel(found.item.type), [found.item.platform,found.item.server].filter(Boolean).join(' / '),found.item.detail].filter(Boolean));}else{setSelection(found.item.label,[typeLabel(found.item.type)],found.item.evidence||[])}}}state.pointer=null;state.dragNode=null;canvas.classList.remove('drag');requestPaint()});canvas.addEventListener('wheel',event=>{event.preventDefault();const rect=canvas.getBoundingClientRect(),point={x:event.clientX-rect.left,y:event.clientY-rect.top},before=world(point),factor=Math.exp(-event.deltaY*.001),next=Math.max(.35,Math.min(2.8,state.camera.scale*factor));state.camera.scale=next;state.camera.x=point.x-before.x*next;state.camera.y=point.y-before.y*next;requestPaint()},{passive:false});
function renderFilters(){filters.replaceChildren();for(const type of [...new Set(state.data.relationships.map(item=>item.type))]){const label=document.createElement('label'),input=document.createElement('input'),text=document.createElement('span');label.className='filter';input.type='checkbox';input.checked=state.types.has(type);input.addEventListener('change',()=>{input.checked?state.types.add(type):state.types.delete(type);requestPaint()});text.textContent=typeLabel(type);label.append(input,text);filters.append(label)}}
async function load(depth){state.depth=depth;status.textContent='读取本地 Kuzu 图谱...';try{const response=await fetch('/api/kuzu-demo/graph?depth='+depth,{cache:'no-store'});if(!response.ok)throw new Error('读取失败');state.data=await response.json();state.types=new Set(state.data.relationships.map(item=>item.type));state.camera={x:0,y:0,scale:1};document.getElementById('account').textContent='账户 '+escapeText(state.data.account);document.getElementById('entities').textContent=state.data.summary.entityCount;document.getElementById('relationships').textContent=state.data.summary.relationshipCount;status.textContent='Kuzu 本地缓存 · '+state.data.depth+' 层';document.querySelectorAll('[data-depth]').forEach(button=>button.classList.toggle('active',Number(button.dataset.depth)===depth));renderFilters();layout();resize()}catch(error){status.textContent='图谱读取失败';setSelection('未能读取图谱',['请确认本机试点图谱文件存在。']);}}
document.querySelectorAll('[data-depth]').forEach(button=>button.addEventListener('click',()=>load(Number(button.dataset.depth))));load(2);
</script></body></html>"""
