from __future__ import annotations


def render_kuzu_focus_workspace_page() -> str:
    """Render the demo-aligned locator/detail relationship workspace."""
    return r'''<!doctype html>
<html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>中心约束关系工作区</title>
<style>
:root{color-scheme:dark;font-family:"Microsoft YaHei","Segoe UI",sans-serif;background:#071426;color:#e4f1ff}
*{box-sizing:border-box}body{margin:0;background:linear-gradient(135deg,#071426,#0b1b31 55%,#06101e);min-height:100vh;overflow:hidden}
.top{height:70px;border-bottom:1px solid #214466;background:#071a31;display:flex;align-items:center;gap:18px;padding:0 20px}.top h1{margin:0;font-size:24px}.top small{color:#82a8d2}.back{color:#b9ddff;border:1px solid #2b79bf;border-radius:8px;padding:9px 13px;text-decoration:none}.toolbar{margin-left:auto;display:flex;gap:9px;align-items:center}.toolbar input{width:70px;background:#0a213a;border:1px solid #3b6790;border-radius:6px;color:#fff;padding:8px}.toolbar button{background:#087ee1;color:white;border:1px solid #40adff;border-radius:7px;padding:9px 13px;cursor:pointer}.toolbar button.alt{background:#142b48;border-color:#376084}.toggle{font-size:12px;color:#9db9d9;white-space:nowrap}.workspace{height:calc(100vh - 70px);display:grid;grid-template-columns:255px minmax(520px,1fr) 320px;gap:12px;padding:12px}.panel{border:1px solid #24496e;background:#08182b;border-radius:12px;overflow:hidden;min-width:0}.panel-head{height:48px;padding:13px 15px;border-bottom:1px solid #204466;font-weight:700}.panel-head span{float:right;color:#7ea6d1;font-size:12px;font-weight:400}.locator{height:100%;display:flex;flex-direction:column}.locator svg{flex:1;width:100%;min-height:0}.locator-note{padding:10px 13px;color:#8eacd0;font-size:12px;line-height:1.5;border-top:1px solid #204466}.detail{position:relative}.detail svg{width:100%;height:100%;display:block}.loading{position:absolute;inset:48px 0 0;display:grid;place-items:center;background:#071426dd;color:#9cc5eb;z-index:3}.loading[hidden]{display:none}.progress{position:absolute;left:14px;bottom:13px;background:#0b213b;border:1px solid #315b84;color:#a9c7e7;border-radius:7px;padding:7px 10px;font-size:12px;z-index:2}.side{padding:14px;overflow:auto}.side h2{margin:0 0 4px;font-size:18px}.side p{margin:5px 0 14px;color:#8facd0;line-height:1.5;font-size:13px}.card{border:1px solid #274f77;background:#0d2744;border-radius:9px;padding:11px;margin:9px 0}.card h3{margin:0 0 6px;font-size:14px;color:#d9edff}.card .muted{color:#92b2d4;font-size:12px}.evidence{border-left:3px solid var(--c,#5dbbff);padding:8px 9px;background:#0b2038;margin:7px 0;font-size:12px;line-height:1.45}.legend{display:grid;grid-template-columns:1fr 1fr;gap:7px;color:#a6c0df;font-size:12px;margin-top:14px}.legend i{font-style:normal}.legend i:before{content:"";display:inline-block;width:10px;height:10px;border-radius:50%;background:var(--c);margin-right:5px}.error{color:#ffadb5;background:#3b1d26;border:1px solid #a44657;padding:10px;border-radius:7px}
.ring{fill:none;stroke:#2d567d;stroke-dasharray:4 8;opacity:.7}.edge{fill:none;stroke-width:2.2;opacity:1;cursor:pointer}.edge:hover{stroke-width:4;opacity:1}.edge.active{stroke-width:4.5;opacity:1}.edge.dim{opacity:1;stroke-width:1.8}.node.dim{opacity:.35}.edge-label{font-size:11px;paint-order:stroke;stroke:#071426;stroke-width:4px;stroke-linejoin:round;pointer-events:none}.cluster{fill-opacity:.09;stroke-width:1.6;stroke-dasharray:5 5}.cluster-label{font-size:12px;font-weight:700;paint-order:stroke;stroke:#071426;stroke-width:4px}.node{stroke:#e5f4ff;stroke-width:1.8;cursor:pointer}.node.subject{stroke:#fff;stroke-width:3}.node.selected{stroke:#fff;stroke-width:4}.status{font-size:11px;text-anchor:middle;dominant-baseline:middle;fill:#071426;font-weight:900;pointer-events:none}.label{font-size:12px;text-anchor:middle;fill:#eff7ff;paint-order:stroke;stroke:#071426;stroke-width:4px;pointer-events:none}.leaf{fill:#34d399;stroke:#c3ffe5;stroke-width:1.2}.leaf-text{font-size:9px;text-anchor:middle;dominant-baseline:middle;fill:#052016;font-weight:900}.ib{stroke:#ffe27b;stroke-width:2}.locator .loc-ring{fill:none;stroke:#315c85;stroke-dasharray:4 8}.locator .loc-node{stroke:#bce5ff;stroke-width:1.2}.locator .loc-current{stroke:#fff;stroke-width:3}.locator .loc-line{stroke:#5bbaff;stroke-width:1;opacity:.45}.locator text{font-size:10px;fill:#8fb0d5}
.detail-link{display:inline-block;margin-top:10px;padding:8px 12px;border-radius:7px;background:#087ee1;border:1px solid #4ab3ff;color:#fff;text-decoration:none;font-weight:700}.detail-link:hover{background:#1594f5}
@media(max-width:1100px){.workspace{grid-template-columns:205px minmax(420px,1fr) 270px}.top small{display:none}}@media(max-width:820px){body{overflow:auto}.workspace{height:auto;min-height:calc(100vh - 70px);grid-template-columns:1fr}.locator{height:220px}.detail{height:620px}.side{min-height:260px}}
</style></head><div data-graph-type="focus-force" hidden>中心约束力导向图</div>
<body><header class="top"><a class="back" href="/kuzu-risk?graph_type=choose">← 图类型</a><h1>中心约束关系工作区</h1><small>全局定位 · 群落聚合 · 证据链路</small><div class="toolbar"><label>阈值 <input id="threshold" type="number" min="1" max="100" value="12"></label><label class="toggle"><input id="toxic" type="checkbox">包含 Toxic</label><button id="reload">重新计算</button><button id="galaxy" class="alt">星系图</button></div></header>
<main class="workspace"><section class="panel locator"><div class="panel-head">全局定位图 <span id="locCount">加载中</span></div><svg id="locator" viewBox="0 0 255 600" aria-label="关系网络全局定位图"></svg><div class="locator-note">左侧只显示当前调查点在全平台关系群落中的位置；点击圈层或节点可定位详细图。</div></section>
<section class="panel detail"><div class="panel-head">详细关系图 <span id="detailMeta">分层展开中</span></div><div id="loading" class="loading">正在读取首层关系…</div><svg id="detailSvg" viewBox="0 0 900 700" aria-label="中心约束关系详细图"></svg><div id="progress" class="progress">等待查询</div></section>
<aside class="panel side"><h2 id="sideTitle">选择一个节点</h2><p id="sideIntro">中心账户固定在中间。点击账户、群落或连线，查看真实关系与完整路径。</p><div id="sideBody" class="card">数据加载完成后可查看证据。</div><div class="legend"><i style="--c:#56aaf5">同 CRM（群组）</i><i style="--c:#a78bfa">LastIP</i><i style="--c:#22d3ee">EA</i><i style="--c:#f472b6">跟单/订单同步</i><i style="--c:#fbbf24">返佣 / IB</i><i style="--c:#fb7185">Toxic</i><i style="--c:#34d399">停止扩散</i><i style="--c:#ff3047">高风险/中心</i></div></aside></main>
<script>
(()=>{const qs=new URLSearchParams(location.search),account=qs.get('account')||'',platform=qs.get('platform')||'',server=qs.get('server')||'';const svg=document.getElementById('detailSvg'),loc=document.getElementById('locator'),loading=document.getElementById('loading'),progress=document.getElementById('progress'),sideTitle=document.getElementById('sideTitle'),sideIntro=document.getElementById('sideIntro'),sideBody=document.getElementById('sideBody'),meta=document.getElementById('detailMeta'),locCount=document.getElementById('locCount');const C={same_crm_user:'#56aaf5',crm_owner:'#56aaf5',login_ip:'#a78bfa',ea_feature:'#22d3ee',copy_order:'#f472b6',copy_group:'#f472b6',rebate:'#fbbf24',direct_ib:'#fbbf24',ib_owned_account:'#fbbf24',ib_direct_account:'#fbbf24',ib_identity:'#fbbf24',ib_direct_rebate:'#fbbf24',top_ib_group:'#fbbf24',toxic_sync_same:'#fb7185',toxic_sync_opposite:'#fb7185',same_name:'#34d399'};const S={data:null,nodes:[],edges:[],by:new Map(),subject:'',selected:null,scale:1,panX:0,panY:0};const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));const id=v=>String(v??'').trim();const hash=s=>{let h=2166136261;for(const c of String(s)){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return(h>>>0)/4294967296};const edgeColor=e=>C[e.type]||'#5d8ab5';const status=n=>id(n.databaseStatus||n.status||'B').toUpperCase()||'B';const radius=n=>n.isSubject?34:22+(['T','TA','A','P'].includes(status(n))?7:0)+Math.min(10,Number(n.score||0)/18);
  function endpoint(){const p=new URLSearchParams({threshold:String(document.getElementById('threshold').value||12),include_toxic:document.getElementById('toxic').checked?'true':'false'});if(platform)p.set('platform',platform);if(server)p.set('server',server);return account?'/api/accounts/by-login/'+encodeURIComponent(account)+'/relationship-network?'+p:'/api/kuzu-risk/graph?threshold='+p.get('threshold')}
  function normalize(payload){S.data=payload||{};const graph=payload?.presentationGraph||payload;const raws=Array.isArray(graph?.entities)?graph.entities:[];S.nodes=raws.map((n,i)=>({...n,id:id(n.id||n.account||n.label||i),status:status(n),r:radius(n),x:0,y:0}));S.subject=id(graph?.subjectId)||S.nodes.find(n=>n.isSubject||n.subject)?.id||S.nodes[0]?.id||'';S.by=new Map(S.nodes.map(n=>[n.id,n]));S.edges=(graph?.relationships||[]).map((e,i)=>({...e,id:id(e.id)||'e'+i,source:id(e.source||e.from),target:id(e.target||e.to),type:e.type||'',label:e.typeLabel||e.label||e.type||'关系'})).filter(e=>S.by.has(e.source)&&S.by.has(e.target));const rings={};S.nodes.forEach(n=>{if(n.id===S.subject){n.x=0;n.y=0;return}const h=Math.max(1,Number(n.hops||1)), a=hash(n.id)*Math.PI*2, r=n.type==='relation_group'?110+h*125:145+h*145; n.x=Math.cos(a)*r;n.y=Math.sin(a)*r;(rings[h]??=[]).push(n)});for(const list of Object.values(rings)){list.forEach((n,i)=>{const a=(i/Math.max(1,list.length))*Math.PI*2+hash(n.id)*.25;const r=Math.hypot(n.x,n.y);n.x=Math.cos(a)*r;n.y=Math.sin(a)*r})}}
  function groupData(){const groups=new Map();S.edges.forEach(e=>{const a=S.by.get(e.source),b=S.by.get(e.target),entity=a?.type==='relation_group'?a:b?.type==='relation_group'?b:null;const key=entity?`group:${entity.id}`:(e.type||'other');if(!groups.has(key))groups.set(key,[]);groups.get(key).push(e)});return groups}
  function fitClusterEllipse(members,cx,cy){let rx=Math.max(80,...members.map(n=>Math.abs(n.x-cx)+n.r)),ry=Math.max(55,...members.map(n=>Math.abs(n.y-cy)+n.r));const scale=Math.max(1,...members.map(n=>Math.sqrt(((Math.abs(n.x-cx)+n.r)/rx)**2+((Math.abs(n.y-cy)+n.r)/ry)**2)));return{rx:rx*scale+28,ry:ry*scale+28}}
  function path(a,b,i){const dx=b.x-a.x,dy=b.y-a.y,d=Math.max(1,Math.hypot(dx,dy)),m=((hash(i)-.5)*2)*Math.min(80,d*.22);return`M${a.x},${a.y} Q${(a.x+b.x)/2-dy/d*m},${(a.y+b.y)/2+dx/d*m} ${b.x},${b.y}`}
  function render(){svg.innerHTML='';const root=document.createElementNS('http://www.w3.org/2000/svg','g');root.setAttribute('transform',`translate(${450+S.panX} ${350+S.panY}) scale(${S.scale})`);svg.appendChild(root);[150,300,450,600].forEach(r=>{const c=document.createElementNS('http://www.w3.org/2000/svg','circle');c.setAttribute('class','ring');c.setAttribute('r',r);root.appendChild(c)});const active=new Set(),activeNodes=new Set();if(S.selected){let cur=S.selected;activeNodes.add(cur);for(let guard=0;guard<20&&cur!==S.subject;guard++){const e=S.edges.find(x=>x.source===cur||x.target===cur);if(!e)break;active.add(e.id);cur=e.source===cur?e.target:e.source;activeNodes.add(cur)}}else S.nodes.forEach(n=>activeNodes.add(n.id));
    const labelBoxes=[];const placeClusterLabel=(x,y,text)=>{const w=Math.max(72,text.length*7.5),h=19,offsets=[0,-24,24,-48,48,-72,72,-96,96];for(const dy of offsets){const box={x,y:y+dy-h,w,h};if(!labelBoxes.some(b=>box.x<b.x+b.w+12&&box.x+box.w+12>b.x&&box.y<b.y+b.h+8&&box.y+box.h+8>b.y)){labelBoxes.push(box);return{x,y:y+dy}}}const last=labelBoxes[labelBoxes.length-1];const placed={x,y:(last?.y||y)+h+12};labelBoxes.push({x:placed.x,y:placed.y-h,w,h});return placed};
    const groups=groupData();for(const [type,edges] of groups){const all=[...new Set(edges.flatMap(e=>[e.source,e.target]).filter(x=>x!==S.subject))].map(x=>S.by.get(x)).filter(Boolean);const members=all.filter(n=>n.type==='account');if(!members.length)continue;const cx=members.reduce((s,n)=>s+n.x,0)/members.length,cy=members.reduce((s,n)=>s+n.y,0)/members.length,{rx,ry}=fitClusterEllipse(members,cx,cy);const el=document.createElementNS('http://www.w3.org/2000/svg','ellipse');el.setAttribute('class','cluster');el.setAttribute('cx',cx);el.setAttribute('cy',cy);el.setAttribute('rx',rx);el.setAttribute('ry',ry);const groupEntity=all.find(n=>n.type==='relation_group');const relationType=groupEntity?.relationType||edges[0].type;el.setAttribute('stroke',C[relationType]||'#5d8ab5');root.appendChild(el);const label=(groupEntity?.label||edges[0].typeLabel||type)+' · '+members.length+'个账户',pos=placeClusterLabel(cx-rx+10,cy-ry+18,label),tx=document.createElementNS('http://www.w3.org/2000/svg','text');tx.setAttribute('class','cluster-label');tx.setAttribute('x',pos.x);tx.setAttribute('y',pos.y);tx.setAttribute('fill',C[relationType]||'#5d8ab5');tx.textContent=label;root.appendChild(tx)}
    const edgeLayer=document.createElementNS('http://www.w3.org/2000/svg','g');root.appendChild(edgeLayer);
    const drawEdge=(e,a,b,label=e.label)=>{const p=document.createElementNS('http://www.w3.org/2000/svg','path');p.setAttribute('class','edge '+(S.selected&&active.has(e.id)?'active ':'')+(S.selected&&!active.has(e.id)?'dim':''));p.setAttribute('stroke',edgeColor(e));p.setAttribute('d',path(a,b,e.id));p.addEventListener('click',()=>{S.selected=e.source;render();show(e.source,e)});edgeLayer.appendChild(p);const t=document.createElementNS('http://www.w3.org/2000/svg','text');t.setAttribute('class','edge-label '+(S.selected&&!active.has(e.id)?'dim':''));t.setAttribute('x',(a.x+b.x)/2);t.setAttribute('y',(a.y+b.y)/2);t.setAttribute('fill',edgeColor(e));t.textContent=label;edgeLayer.appendChild(t)};
    if(S.selected){S.edges.forEach(e=>{const a=S.by.get(e.source),b=S.by.get(e.target);if(a&&b&&(e.source===S.selected||e.target===S.selected||active.has(e.id)))drawEdge(e,a,b)});}else{
      const relationEdges=S.edges.filter(e=>S.by.get(e.source)?.type==='relation_group'||S.by.get(e.target)?.type==='relation_group');
      relationEdges.forEach(e=>{const a=S.by.get(e.source),b=S.by.get(e.target);if(a&&b)drawEdge(e,a,b,e.label)});
      if(relationEdges.length){ /* collapsed relation entities replace pairwise account edges */ }
      else {
      const grouped=new Map();S.edges.forEach(e=>{const a=S.by.get(e.source),b=S.by.get(e.target);if(!a||!b)return;const key=e.type||'other';const g=grouped.get(key)||{edges:[],nodes:[]};g.edges.push(e);if(a.id!==S.subject)g.nodes.push(a);if(b.id!==S.subject)g.nodes.push(b);grouped.set(key,g)});
      grouped.forEach((g,type)=>{const members=[...new Map(g.nodes.map(n=>[n.id,n])).values()];if(!members.length)return;const target={x:members.reduce((s,n)=>s+n.x,0)/members.length,y:members.reduce((s,n)=>s+n.y,0)/members.length};const base=g.edges[0];const label=(base.typeLabel||base.label||type)+` · ${members.length}个账户`;drawEdge({...base,id:'group:'+type},S.by.get(S.subject),target,label)});
      }
    }
    const nodes=document.createElementNS('http://www.w3.org/2000/svg','g');root.appendChild(nodes);S.nodes.forEach(n=>{const g=document.createElementNS('http://www.w3.org/2000/svg','g');g.setAttribute('transform',`translate(${n.x} ${n.y})`);g.setAttribute('class',S.selected&&!activeNodes.has(n.id)?'dim':'');g.addEventListener('click',()=>{S.selected=n.id;render();show(n.id)});const relationPill=n.type!=='account'&&n.type!=='ib';let shape=document.createElementNS('http://www.w3.org/2000/svg',n.type==='ib'?'polygon':relationPill?'rect':'circle');if(shape.tagName==='polygon'){const r=n.r;shape.setAttribute('points',`0,${-r} ${r*.86},${-r*.5} ${r*.86},${r*.5} 0,${r} ${-r*.86},${r*.5} ${-r*.86},${-r*.5}`)}else if(shape.tagName==='rect'){shape.setAttribute('x',-n.r*1.5);shape.setAttribute('y',-n.r*.55);shape.setAttribute('width',n.r*3);shape.setAttribute('height',n.r*1.1);shape.setAttribute('rx',n.r*.55)}else shape.setAttribute('r',n.r);shape.setAttribute('class','node '+(n.isSubject?'subject ':'')+(S.selected===n.id?'selected ':'')+(n.type==='ib'?'ib':''));shape.setAttribute('fill',n.isSubject?'#ff3047':(relationPill?'#16385c':(n.riskColor||'#f28b30')));g.appendChild(shape);const st=document.createElementNS('http://www.w3.org/2000/svg','text');st.setAttribute('class','status');st.textContent=n.type==='account'?n.status:(n.type==='relation_group'?'群组':'关系');g.appendChild(st);if(n.expandable===false&&n.type==='account'){const lf=document.createElementNS('http://www.w3.org/2000/svg','circle');lf.setAttribute('class','leaf');lf.setAttribute('cx',n.r*.72);lf.setAttribute('cy',-n.r*.72);lf.setAttribute('r',8);g.appendChild(lf);const lt=document.createElementNS('http://www.w3.org/2000/svg','text');lt.setAttribute('class','leaf-text');lt.setAttribute('x',n.r*.72);lt.setAttribute('y',-n.r*.72);lt.textContent='停';g.appendChild(lt)}const l=document.createElementNS('http://www.w3.org/2000/svg','text');l.setAttribute('class','label');l.setAttribute('y',relationPill?n.r*.95:n.r+17);l.textContent=n.label||n.id;g.appendChild(l);nodes.appendChild(g)})}
  function renderLocator(){loc.innerHTML='';const cx=127,cy=285;[55,100,145,190,235].forEach(r=>{const c=document.createElementNS('http://www.w3.org/2000/svg','circle');c.setAttribute('class','loc-ring');c.setAttribute('cx',cx);c.setAttribute('cy',cy);c.setAttribute('r',r);loc.appendChild(c)});const sub=S.by.get(S.subject);S.nodes.filter(n=>n.id!==S.subject).forEach(n=>{const h=Math.min(4,Math.max(1,Number(n.hops||1))),a=hash(n.id)*Math.PI*2,r=55+h*45,x=cx+Math.cos(a)*r,y=cy+Math.sin(a)*r;const line=document.createElementNS('http://www.w3.org/2000/svg','line');line.setAttribute('class','loc-line');line.setAttribute('x1',cx);line.setAttribute('y1',cy);line.setAttribute('x2',x);line.setAttribute('y2',y);loc.appendChild(line);const d=document.createElementNS('http://www.w3.org/2000/svg','circle');d.setAttribute('class','loc-node '+(S.selected===n.id?'loc-current':''));d.setAttribute('cx',x);d.setAttribute('cy',y);d.setAttribute('r',n.isSubject?9:5);d.setAttribute('fill',n.riskColor||'#ef8b32');d.addEventListener('click',()=>{S.selected=n.id;render();show(n.id)});loc.appendChild(d)});const d=document.createElementNS('http://www.w3.org/2000/svg','circle');d.setAttribute('class','loc-node loc-current');d.setAttribute('cx',cx);d.setAttribute('cy',cy);d.setAttribute('r',10);d.setAttribute('fill','#ff3047');loc.appendChild(d);const t=document.createElementNS('http://www.w3.org/2000/svg','text');t.setAttribute('x',cx-35);t.setAttribute('y',cy+28);t.textContent=S.subject||'中心';loc.appendChild(t);locCount.textContent=`${S.nodes.length}个节点`}
  function accountHref(n){const p=new URLSearchParams();if(n.platform||platform)p.set('platform',n.platform||platform);if(n.server||server)p.set('server',n.server||server);return'/account/'+encodeURIComponent(n.account||n.login||n.label||n.id)+(p.toString()?'?'+p.toString():'')}
  function show(nodeId,edge){const n=S.by.get(nodeId);if(!n)return;const inc=S.edges.filter(e=>e.source===nodeId||e.target===nodeId);const isAccount=n.type==='account';const display=isAccount?(n.account||n.login||n.label||n.id):(n.label||n.detail||n.id);sideTitle.textContent=isAccount?`账户 ${display}`:`关系实体 ${display}`;sideIntro.textContent=isAccount?(n.isSubject?'这是调查起点。所有关系路径从这里开始。':`第 ${n.hops||0} 圈 · 与中心账户的关系链路已高亮。`):'这是关系聚合节点，不是交易账户；点击关联账户查看账户详情。';const accountButton=isAccount?`<a class="detail-link" href="${esc(accountHref(n))}">查看账户详情</a>`:'';sideBody.innerHTML=isAccount?`<div class="card"><h3>账户状态：${esc(n.status||'B')}</h3><div class="muted">分值 ${Number(n.score||0).toFixed(1)} · ${n.expandable===false?'叶子节点，停止扩散':'继续检查'}</div>${accountButton}</div>`:`<div class="card"><h3>关系类型：${esc(n.relationType||n.typeLabel||n.type||'关系')}</h3><div class="muted">${esc(n.detail||'该节点代表一组共同关系证据')}</div></div>`;sideBody.innerHTML+=`<div class="card"><h3>关系证据（${inc.length}）</h3>${inc.map(e=>`<div class="evidence" style="--c:${edgeColor(e)}"><b style="color:${edgeColor(e)}">${esc(e.label)}</b><br>${esc(e.evidence||'关系接口返回的证据')}</div>`).join('')||'<div class="muted">暂无直接证据</div>'}</div>${edge?`<div class="card"><h3>当前链路</h3><div class="muted">${esc(edge.source)} → ${esc(edge.target)} · ${esc(edge.label)}</div></div>`:''}`}
  async function stage(){const res=await fetch(endpoint(),{cache:'no-store'});if(!res.ok)throw new Error('关系接口返回 '+res.status);const p=await res.json();normalize(p);render();renderLocator();meta.textContent=`${S.nodes.length}节点 · ${S.edges.length}条关系`;const state=p.progress||{},expanded=Number(state.expandedAccounts||p.summary?.discoveryAccountCount||0),pending=Number(state.pendingAccounts||p.summary?.pendingAccountCount||0);progress.textContent=p.inProgress?`后台扩散中：已处理 ${expanded} 个账户，待处理 ${pending} 个`:(p.discoveryTruncated?'达到查询预算，已保留当前结果':'扩散完成');loading.hidden=S.nodes.length>0||!p.inProgress;return p}
  async function load(){loading.hidden=false;try{for(let poll=0;poll<180;poll++){const p=await stage();if(!p.inProgress)return;await new Promise(resolve=>setTimeout(resolve,500))}throw new Error('关系扩散仍在后台运行，请稍后重新打开')}catch(e){loading.hidden=true;sideBody.innerHTML=`<div class="error">${esc(e.message||e)}</div>`}}
  document.getElementById('reload').onclick=load;document.getElementById('galaxy').onclick=()=>{const u=new URL('/kuzu-risk',location.origin);qs.forEach((v,k)=>u.searchParams.set(k,v));u.searchParams.set('graph_type','galaxy');location.assign(u)};svg.addEventListener('wheel',e=>{e.preventDefault();S.scale=Math.max(.1,Math.min(2.8,S.scale*(e.deltaY<0?1.15:.86)));render()},{passive:false});let drag=null;svg.addEventListener('pointerdown',e=>drag={x:e.clientX,y:e.clientY,px:S.panX,py:S.panY});window.addEventListener('pointermove',e=>{if(!drag)return;S.panX+=e.clientX-drag.x;S.panY+=e.clientY-drag.y;drag.x=e.clientX;drag.y=e.clientY;render()});window.addEventListener('pointerup',()=>drag=null);load();})();
</script></body></html>'''
