from __future__ import annotations


def relation_display_assets() -> str:
    """Shared, DOM-safe relation-table client used by both relationship renderers."""
    return r'''<style>
.relation-display{position:fixed;z-index:80;right:16px;top:76px;bottom:16px;width:min(520px,calc(100vw - 32px));display:none;flex-direction:column;overflow:hidden;border:1px solid #3a6f9f;border-radius:12px;background:#071b2e;box-shadow:0 18px 58px #0009;color:#e6f2ff}.relation-display.open{display:flex}.relation-display-head{display:flex;align-items:flex-start;justify-content:space-between;gap:12px;padding:16px;border-bottom:1px solid #244967;background:#0a2741}.relation-display-head h2{margin:0;font-size:20px}.relation-display-head p{margin:5px 0 0;color:#a8c4df;font-size:12px;line-height:1.45}.relation-display-close{border:1px solid #507c9f;background:#102e48;color:#dceeff;border-radius:6px;padding:5px 9px;cursor:pointer}.relation-display-body{overflow:auto;padding:14px}.relation-display-card{margin:0 0 12px;padding:12px;border:1px solid #2d5c82;border-radius:9px;background:#09243a}.relation-display-card h3{margin:0 0 8px;font-size:14px}.relation-display-coverage{color:#b8cfe2;font-size:12px;line-height:1.55}.relation-display-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:7px}.relation-display-metric{padding:8px;border-radius:6px;background:#0d304d}.relation-display-metric span{display:block;color:#a7c1d8;font-size:11px}.relation-display-metric b{display:block;margin-top:3px;color:#fff;font-size:14px;word-break:break-word}.relation-display-actions{display:flex;gap:8px;flex-wrap:wrap}.relation-display-actions button{border:1px solid #3d789f;background:#123a5b;color:#eaf6ff;border-radius:6px;padding:7px 9px;cursor:pointer}.relation-display-actions button.primary{background:#1764a0;border-color:#50b8ed}.relation-display-member{width:100%;margin:0 0 8px;padding:10px;border:1px solid #2d5c82;border-radius:8px;background:#09243a;color:#e7f4ff;text-align:left;cursor:pointer}.relation-display-member:hover{border-color:#62c7ff;background:#0d3150}.relation-display-member strong{font-size:16px}.relation-display-member small{display:block;margin-top:3px;color:#a9c5de}.relation-display-evidence{color:#b8cee1;font-size:12px;line-height:1.55;white-space:pre-wrap}.relation-display-error{color:#fecaca;padding:12px;border:1px solid #a34a55;border-radius:8px;background:#391923}.relation-display-loading{color:#b8d6ed;padding:14px}.relation-display-pager{display:flex;align-items:center;justify-content:space-between;gap:8px;color:#a9c5de;font-size:12px}.relation-display-pager button{border:1px solid #3d789f;background:#123a5b;color:#eaf6ff;border-radius:5px;padding:5px 8px;cursor:pointer}.relation-display-pager button:disabled{opacity:.45;cursor:not-allowed}@media(max-width:700px){.relation-display{top:10px;right:10px;bottom:10px;width:calc(100vw - 20px)}.relation-display-grid{grid-template-columns:1fr}}
</style><script>
(()=>{
  const text=value=>String(value??'');
  const node=(tag,className='')=>{const item=document.createElement(tag);if(className)item.className=className;return item};
  let shell,body,title,subtitle,current;
  function ensure(){if(shell)return;shell=node('aside','relation-display');shell.setAttribute('aria-label','关系展示表');const head=node('header','relation-display-head'),heading=node('div');title=node('h2');subtitle=node('p');heading.append(title,subtitle);const close=node('button','relation-display-close');close.type='button';close.textContent='关闭';close.addEventListener('click',()=>shell.classList.remove('open'));head.append(heading,close);body=node('div','relation-display-body');shell.append(head,body);document.body.append(shell)}
  function paramsFor(edgeId,scope,page){const params=new URLSearchParams(current?.params||location.search);params.set('edge_id',edgeId);params.set('scope',scope);params.set('member_page',String(page));params.set('member_limit','50');if(current?.snapshotVersion!==undefined&&current?.snapshotVersion!==null)params.set('snapshot_version',String(current.snapshotVersion));return params}
  function endpoint(edgeId,scope,page){return '/api/accounts/by-login/'+encodeURIComponent(current.target)+'/relationship-network/relation-display?'+paramsFor(edgeId,scope,page).toString()}
  function metricGrid(metrics){const grid=node('div','relation-display-grid');for(const item of metrics||[]){const card=node('div','relation-display-metric'),label=node('span'),value=node('b');label.textContent=text(item.label);value.textContent=text(item.value)+(item.unit&&item.unit!=='%'?' '+item.unit:item.unit==='%'?'%':'');card.append(label,value);grid.append(card)}return grid}
  function renderEvidence(items){const card=node('section','relation-display-card'),heading=node('h3');heading.textContent='原始关系证据';card.append(heading);if(!items?.length){const empty=node('div','relation-display-evidence');empty.textContent='当前关系未返回可展示的原始证据。';card.append(empty);return card}for(const item of items){const row=node('div','relation-display-evidence');row.textContent=text(item);card.append(row)}return card}
  async function loadRawEvidence(edgeId){const url='/api/accounts/by-login/'+encodeURIComponent(current.target)+'/relationship-network/relation-detail?'+paramsFor(edgeId,'auto',1).toString();const response=await fetch(url,{cache:'no-store'});if(!response.ok)throw new Error('原始关系证据读取失败');const data=await response.json();return (data.relations||[]).flatMap(item=>item.evidence||[])}
  function actions(display,edgeId,scope,page){const box=node('div','relation-display-actions');for(const action of display.group_actions||[]){const button=node('button',action.id==='open_group'?'primary':'');button.type='button';button.textContent=text(action.label);button.addEventListener('click',async()=>{if(action.id==='open_group'){await open(edgeId,'group',1);return}if(action.id==='relation_detail'){button.disabled=true;try{const evidence=await loadRawEvidence(edgeId);const existing=body.querySelector('[data-raw-evidence]')||renderEvidence(evidence);existing.dataset.rawEvidence='true';if(!existing.parentElement)body.append(existing)}catch(error){const issue=node('div','relation-display-error');issue.textContent=text(error.message||error);body.append(issue)}finally{button.disabled=false}}});box.append(button)}return box}
  function memberList(display,edgeId,scope,page){const card=node('section','relation-display-card'),heading=node('h3'),memberPage=display.member_page||{};heading.textContent='成员明细（'+text(memberPage.total||0)+'）';card.append(heading);for(const item of memberPage.items||[]){const button=node('button','relation-display-member'),account=item.account||{},name=node('strong'),route=node('small');button.type='button';name.textContent=text(account.login||account.node_id);route.textContent=[account.platform,account.server,account.database_status?'状态 '+account.database_status:''].filter(Boolean).join(' · ');button.append(name,route);if((item.metrics||[]).length)button.append(metricGrid(item.metrics));button.addEventListener('click',()=>current?.onSelectMember?.(account.node_id));card.append(button)}if((memberPage.total||0)>memberPage.limit){const pager=node('div','relation-display-pager'),previous=node('button'),pageLabel=node('span'),next=node('button');previous.type=next.type='button';previous.textContent='上一页';next.textContent='下一页';pageLabel.textContent='第 '+page+' 页';previous.disabled=page<=1;next.disabled=page*memberPage.limit>=memberPage.total;previous.addEventListener('click',()=>open(edgeId,scope,page-1));next.addEventListener('click',()=>open(edgeId,scope,page+1));pager.append(previous,pageLabel,next);card.append(pager)}return card}
  function render(display,edgeId,scope,page){body.replaceChildren();const relation=display.relation||{},coverage=display.coverage||{};title.textContent='关系展示表 · '+text(relation.label||relation.type);subtitle.textContent=text(relation.direction||'关系事实')+' · '+text(relation.anchor?.label||'');const coverageCard=node('section','relation-display-card'),coverageText=node('div','relation-display-coverage');coverageText.textContent='总成员 '+text(coverage.known_members)+' · 当前图谱纳入 '+text(coverage.included_members)+' · 实际统计 '+text(coverage.statistic_members)+' · 覆盖 '+text(coverage.status)+'。'+text(coverage.reason);coverageCard.append(coverageText);body.append(coverageCard);const metrics=display.mode==='group'?display.summary_metrics:display.single_metrics;if(metrics?.length){const metricsCard=node('section','relation-display-card'),heading=node('h3');heading.textContent=display.mode==='group'?'关系汇总':'该账号在此关系中的情况';metricsCard.append(heading,metricGrid(metrics));body.append(metricsCard)}body.append(actions(display,edgeId,scope,page));if(display.mode==='group')body.append(memberList(display,edgeId,scope,page));body.append(renderEvidence(display.evidence))}
  async function open(edgeId,scope='auto',page=1){ensure();shell.classList.add('open');body.replaceChildren();const loading=node('div','relation-display-loading');loading.textContent='正在读取关系展示表…';body.append(loading);try{const response=await fetch(endpoint(edgeId,scope,page),{cache:'no-store'});if(response.status===409)throw new Error('调查快照已更新，请刷新关系图后重试');if(!response.ok)throw new Error('关系展示表读取失败');render(await response.json(),edgeId,scope,page)}catch(error){body.replaceChildren();const issue=node('div','relation-display-error');issue.textContent=text(error.message||error);body.append(issue)}}
  window.KdeskRelationDisplay={open(context,edgeId,scope='auto'){current=context;return open(edgeId,scope,1)},close(){shell?.classList.remove('open')}};
})();
</script>'''
